### ISSUE TITLE
Incompatibility with recent Nextflow version

### ISSUE THREAD

**Issue by Cecilia-Sensalari** [VIB-PSB/ksrates#39]
As pointed out in issue #38, the Nextflow pipeline implemented in `main.nf` is not compatible anymore with recent Nextflow versions (the issue refers to version 22.04.0.5697). It gives the following error message:
```
$ nextflow run VIB-PSB/ksrates --config ./config_elaeis.txt
N E X T F L O W  ~  version 22.04.0
Launching `https://github.com/VIB-PSB/ksrates` [determined_bernard] DSL2 - revision: bfbb623720 [master]


K S R A T E S   -   N E X T F L O W   P I P E L I N E   (v1.1.1)
----------------------------------------------------------------

Configuration file:                    ./config_elaeis.txt
Logs folder:                           logs_3cf4463c
Preserve leftover files:               false

Command line:               nextflow run VIB-PSB/ksrates --config ./config_elaeis.txt
Launch directory:           /Users/wickell/ksrates
Work directory:             /Users/wickell/ksrates/work
ksrates directory:          /Users/wickell/.nextflow/assets/VIB-PSB/ksrates

Start time:                 2022-04-28T09:05:59.358787-04:00


No such variable: outCheckConfig

 -- Check script '/Users/wickell/.nextflow/assets/VIB-PSB/ksrates/main.nf' at line: 252 or see '.nextflow.log' file for more details
```

A quick way to fix this problem is to make use of the older Nextflow version used to develop ksrates (21.10.6.5660) by adding the NXF_VER environmental variable in the command line (see Nextflow [docs](https://www.nextflow.io/docs/latest/getstarted.html#updates)):
```
 NXF_VER=21.10.6 nextflow run VIB-PSB/ksrates --config ./config_elaeis.txt
```

The actual fix will have to identify the cause of this incompatibility and edit the affected lines in `main.nf`.

**Comment by major-one** [comment]
Hello 

- [ ] @Cecilia-Sensalari

After I try to run, I get an error like this, can you help me?Thank you very much

N E X T F L O W  ~  version 21.10.6
Launching `VIB-PSB/ksrates` [nauseous_torricelli] - revision: bfbb623720 [master]


K S R A T E S   -   N E X T F L O W   P I P E L I N E   (v1.1.1)
----------------------------------------------------------------

Configuration file:                    ./config_elaeis.txt
Logs folder:                           logs_f55ff9e5
Preserve leftover files:               false

Command line:               nextflow run VIB-PSB/ksrates --config ./config_elaeis.txt
Launch directory:           /share/home/stu_wangtianyou/soft/ksrates/test
Work directory:             /share/home/stu_wangtianyou/soft/ksrates/test/work
ksrates directory:          /share/home/stu_wangtianyou/.nextflow/assets/VIB-PSB/ksrates

Start time:                 2022-05-12T16:46:58.801640+08:00


[-        ] process > checkConfig         -
[-        ] process > checkConfig         -
[-        ] process > setupAdjustment     -
[-        ] process > setParalogAnalysis  -
[-        ] process > setOrthologAnalysis -
[-        ] process > estimatePeaks       -
[-        ] process > wgdParalogs         -
[-        ] process > wgdOrthologs        -
[-        ] process > plotOrthologDistrib -
[-        ] process > doRateAdjustment    -
[-        ] process > paralogsAnalyses    -
[-        ] process > drawTree            -
Pulling Singularity image docker://vibpsb/ksrates:latest [cache /share/home/stu_wangtianyou/soft/ksrates/test/work/singularity/vibpsb-ksrates-latest.img]WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /share/home/stu_wangtianyou/soft/ksrates/test/work/singularity -- Use env variable NXF_SINGULARITY_CACHEDIR to specify a different location
Error executing process > 'checkConfig'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name vibpsb-ksrates-latest.img.pulling.1652345220904 docker://vibpsb/ksrates:latest > /dev/null
  status : 1
  message:
[-        ] process > checkConfig         -
[-        ] process > setupAdjustment     -
[-        ] process > setParalogAnalysis  -
[-        ] process > setOrthologAnalysis -
[-        ] process > estimatePeaks       -
[-        ] process > wgdParalogs         -
[-        ] process > wgdOrthologs        -
[-        ] process > plotOrthologDistrib -
[-        ] process > doRateAdjustment    -
[-        ] process > paralogsAnalyses    -
[-        ] process > drawTree            -
Pulling Singularity image docker://vibpsb/ksrates:latest [cache /share/home/stu_wangtianyou/soft/ksrates/test/work/singularity/vibpsb-ksrates-latest.img]
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /share/home/stu_wangtianyou/soft/ksrates/test/work/singularity -- Use env variable NXF_SINGULARITY_CACHEDIR to specify a different location
Error executing process > 'checkConfig'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name vibpsb-ksrates-latest.img.pulling.1652345220904 docker://vibpsb/ksrates:latest > /dev/null
  status : 1  message:
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 1: Bootstrap:: command not found
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 2: From:: command not found
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 4: fg: no job control
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 5: AUTHOR: command not found
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 7: fg: no job control
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 8: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): No such file or directory
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 8: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 12: fg: no job control
    bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
    /share/home/stu_wangtianyou/soft/ksrates/requirements.txt: line 9: scikit-learn==0.24.2: command not found
    bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
    /share/home/stu_wangtianyou/soft/ksrates/setup.py: line 1: from: command not found
    /share/home/stu_wangtianyou/soft/ksrates/setup.py: line 2: from: command not found
    /share/home/stu_wangtianyou/soft/ksrates/setup.py: line 4: syntax error near unexpected token `('
    /share/home/stu_wangtianyou/soft/ksrates/setup.py: line 4: `with open("README.md", 'r') as f:'
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 15: ksrates: command not found
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 16: wgd_ksrates: command not found
    bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
    /share/home/stu_wangtianyou/soft/ksrates/README.md: line 1: syntax error near unexpected token `('
    /share/home/stu_wangtianyou/soft/ksrates/README.md: line 1: `[![Test pipeline CI](https://github.com/VIB-PSB/ksrates/actions/workflows/test_pipeline.yml/badge.svg)](https://github.com/VIB-PSB/ksrates/actions/workflows/test_pipeline.yml)'
    bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
[-        ] process > checkConfig         -
[-        ] process > setupAdjustment     -
[-        ] process > setParalogAnalysis  -
[-        ] process > setOrthologAnalysis -
[-        ] process > estimatePeaks       -
[-        ] process > wgdParalogs         -
[-        ] process > wgdOrthologs        -
[-        ] process > plotOrthologDistrib -
[-        ] process > doRateAdjustment    -
[-        ] process > paralogsAnalyses    -
[-        ] process > drawTree            -
Pulling Singularity image docker://vibpsb/ksrates:latest [cache /share/home/stu_wangtianyou/soft/ksrates/test/work/singularity/vibpsb-ksrates-latest.img]
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /share/home/stu_wangtianyou/soft/ksrates/test/work/singularity -- Use env variable NXF_SINGULARITY_CACHEDIR to specify a different location
Error executing process > 'checkConfig'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name vibpsb-ksrates-latest.img.pulling.1652345220904 docker://vibpsb/ksrates:latest > /dev/null
  status : 1
  message:
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 1: Bootstrap:: command not found
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 2: From:: command not found
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 4: fg: no job control
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 5: AUTHOR: command not found
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 7: fg: no job control
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 8: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): No such file or directory
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 8: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 12: fg: no job control
    bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
    /share/home/stu_wangtianyou/soft/ksrates/requirements.txt: line 9: scikit-learn==0.24.2: command not found
    bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
    /share/home/stu_wangtianyou/soft/ksrates/setup.py: line 1: from: command not found
    /share/home/stu_wangtianyou/soft/ksrates/setup.py: line 2: from: command not found
    /share/home/stu_wangtianyou/soft/ksrates/setup.py: line 4: syntax error near unexpected token `('
    /share/home/stu_wangtianyou/soft/ksrates/setup.py: line 4: `with open("README.md", 'r') as f:'
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 15: ksrates: command not found
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 16: wgd_ksrates: command not found
    bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
    /share/home/stu_wangtianyou/soft/ksrates/README.md: line 1: syntax error near unexpected token `('
    /share/home/stu_wangtianyou/soft/ksrates/README.md: line 1: `[![Test pipeline CI](https://github.com/VIB-PSB/ksrates/actions/workflows/test_pipeline.yml/badge.svg)](https://github.com/VIB-PSB/ksrates/actions/workflows/test_pipeline.yml)'
    bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
    /share/home/stu_wangtianyou/soft/ksrates/ksrates_cli.py: line 1: import: command not found
    /share/home/stu_wangtianyou/soft/ksrates/ksrates_cli.py: line 2: import: command not found
    /share/home/stu_wangtianyou/soft/ksrates/ksrates_cli.py: line 3: from: command not found
    /share/home/stu_wangtianyou/soft/ksrates/ksrates_cli.py: line 4: from: command not found
    /share/home/stu_wangtianyou/soft/ksrates/ksrates_cli.py: line 6: syntax error near unexpected token `context_settings={'help_option_names':'
    /share/home/stu_wangtianyou/soft/ksrates/ksrates_cli.py: line 6: `@click.group(context_settings={'help_option_names': ['-h', '--help']})'
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 20: fg: no job control
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 24: apt-get: command not found
    /share/home/stu_wangtianyou/soft/ksrates/singularity: line 29: apt-get: command not found
    /bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
    Directory '/install' is not installable. File 'setup.py' not found.




 


======================================================================================
The pipeline terminated during process 'checkConfig' with the following error message:

Failed to pull singularity image

More details may be found in the error report above and/or in[.nextflow.log](https://github.com/VIB-PSB/ksrates/files/8677122/default.nextflow.log)
======================================================================================

**Comment by Cecilia-Sensalari** [comment]
Hi @major-one,

Thanks for reporting this. Which command line did you run? Was it including the `NXF_VER=21.10.6` environmental variable as shown in the post above?

**Comment by major-one** [comment]
@Cecilia-Sensalari Thanks for your quick reply，`NXF_VER=21.10.6 nextflow run VIB-PSB/ksrates --config ./config_elaeis.txt` is my command line
