### ISSUE TITLE
ortholog_peak_db.tsv, ortholog_ks_list_db.tsv database are not generated

### ISSUE THREAD

**Issue by B10inform** [VIB-PSB/ksrates#53]
Hi, 
This tool looks great for wgd analysis. I am having issues running it. 
The ortholog_peak_db.tsv, ortholog_ks_list_db.tsv are not generated automatically with the nextflow pipeline. 
Do i need to generate using manual ksrates pipeline?

Thanks,

**Comment by Cecilia-Sensalari** [comment]
Hi,

Thanks for reaching out!
Normally the database files are automatically generated both by the manual pipeline and the Nextflow pipeline. Their file path (or file name) is defined in your [ksrates configuration file](https://ksrates.readthedocs.io/en/latest/configuration.html#ksrates-configuration-file); it will generate them with default names `ortholog_peak_db.tsv` and `ortholog_ks_list_db.tsv` in the launching directory, unless you specify differently.

Could you therefore double-check your launching directory?
To be more in control, you could set for the databases an absolute paths in the configuration file:

```
peak_database_path = /my/absolute/path/to/ortholog_peak_db.tsv
ks_list_database_path = /my/absolute/path/to/ortholog_ks_list_db.tsv
```

Let me know if this helps, and otherwise we look for another reason!

Best,
Cecilia
