### ISSUE TITLE
Difficulty in Output Plots Interpretation

### ISSUE THREAD

**Issue by abcbot123** [VIB-PSB/ksrates#59]
Hi Cecilia,
I have two question regarding my outputs,

1) I didn't get this output "mixed_oxalis_lmm_colinearity.pdf" mentioned in your tutorial. (Ran with expert configuration file). But I got this output file "mixed_species_lmm_paranome.pdf" Can I know the reason for that? 

2) This is regarding the main output file "mixed_oxalis_anchor_clusters.pdf". In this plot, I got just one peak. In the literature, I know that ancient γ event occur. How can I know that one peak is for the ancient γ event or it is species specific WGD? Here I attached the "mixed_oxalis_anchor_clusters.pdf" and "mixed_oxalis_adjusted.pdf" files. Could you please help me to interpret these results. 
[mixed_oxalis_anchor_clusters.pdf](https://github.com/VIB-PSB/ksrates/files/14836964/mixed_oxalis_anchor_clusters.pdf)
[mixed_oxalis_adjusted.pdf](https://github.com/VIB-PSB/ksrates/files/14836966/mixed_oxalis_adjusted.pdf)

**Comment by Cecilia-Sensalari** [comment]
Hi!

Thanks for reaching out. Let's see:

1. To get the LMM for anchors you have to set `colinearity = yes` (paranome doesn't matter) and `extra_paralogs_analyses_methods = yes`. Could you double check that?

2. The clustering in `mixed_oxalis_anchor_clusters.pdf` has been already "cleaned up" of clusters that are likely to be spurious, namely not an actual WGM signal. This can happen when they are very tiny or else widespread over high Ks. In your case, I bet that the ancient gamma peak appears quite flat and widespread around 2.5Ks; its cluster must have been unrightfully removed by the cleanup. I suggest you use another PDF file without filtering, where you should still see the gamma cluster: `mixed_oxalis_anchor_clusters_unfiltered.pdf`, located within the `paralogs_analyses` directory; note that you might also see some other spurious clusters that were instead rightfully removed.

3.  I'll add the last answer as a separate bullet point. Even without having the gamma cluster visible in the plot, the blue cluster "a" is not gamma because it is not shared between Oxalis and Arabidopsis and between Oxalis and Populus: the "a" WGM occurred more recently (0.76 Ks) then the divergence with any of them (1.73 Ks). However, you should also be careful in claiming that it is _specific_ to your focal species, as perhaps there are other closely-related species that do share WGM "a" with it, they are just not included in your plot. A check in literature might help?

Hope this helps,
Cecilia

**Comment by abcbot123** [comment]
Thanks so much Cecilia. This is really helpful.

**Comment by Cecilia-Sensalari** [comment]
Alright! I'll close this issue then.
Cheers,
Cecilia
